export const ALL_PERMISSIONS = [
  'dashboard.view',
  'changes.read',
  'changes.create',
  'changes.update',
  'changes.delete',
  'approvals.read',
  'approvals.approve',
  'users.read',
  'users.create',
  'users.update',
  'users.delete',
  'roles.read',
  'roles.create',
  'roles.update',
  'roles.delete',
  'attachments.read',
  'attachments.upload',
  'attachments.delete',
];

export const ADMIN_MANDATORY_PERMISSIONS = ['dashboard.view', 'changes.read', 'approvals.read'];

export const DEFAULT_ROLE_PERMISSIONS = {
  SuperAdmin: ALL_PERMISSIONS,
  Admin: [
    'dashboard.view',
    'changes.read',
    'changes.create',
    'changes.update',
    'changes.delete',
    'approvals.read',
    'approvals.approve',
    'users.read',
    'users.create',
    'users.update',
    'users.delete',
    'attachments.read',
    'attachments.upload',
    'attachments.delete',
  ],
  Manager: [
    'dashboard.view',
    'changes.read',
    'changes.create',
    'changes.update',
    'approvals.read',
    'approvals.approve',
    'attachments.read',
    'attachments.upload',
    'attachments.delete',
  ],
  User: [
    'dashboard.view',
    'changes.read',
    'changes.create',
    'changes.update',
    'approvals.read',
    'attachments.read',
    'attachments.upload',
  ],
};
