export const ALL_PERMISSIONS = [
  'dashboard.view',
  'changes.read',
  'changes.create',
  'changes.update',
  'changes.delete',
  'approvals.read',
  'approvals.approve',
  'users.read',
  'users.create',
  'users.update',
  'users.delete',
  'roles.read',
  'roles.create',
  'roles.update',
  'roles.delete',
  'attachments.read',
  'attachments.upload',
  'attachments.delete',
  // Masters Page section permissions
  'masters.department.read',
  'masters.department.create',
  'masters.department.update',
  'masters.department.delete',
  'masters.machine.read',
  'masters.machine.create',
  'masters.machine.update',
  'masters.machine.delete',
  'masters.productionline.read',
  'masters.productionline.create',
  'masters.productionline.update',
  'masters.productionline.delete',
  'masters.skill.read',
  'masters.skill.create',
  'masters.skill.update',
  'masters.skill.delete',
  // 4M Guided Setup section permissions
  'guidedsetup.man.read',
  'guidedsetup.man.update',
  'guidedsetup.machine.read',
  'guidedsetup.machine.update',
  'guidedsetup.method.read',
  'guidedsetup.method.update',
  'guidedsetup.material.read',
  'guidedsetup.material.update',
];

export const ADMIN_MANDATORY_PERMISSIONS = ['dashboard.view', 'changes.read', 'approvals.read'];

export const DEFAULT_ROLE_PERMISSIONS = {
  SuperAdmin: ALL_PERMISSIONS,
  Admin: [
    'dashboard.view',
    'changes.read',
    'changes.create',
    'changes.update',
    'changes.delete',
    'approvals.read',
    'approvals.approve',
    'users.read',
    'users.create',
    'users.update',
    'users.delete',
    'roles.read',
    'roles.create',
    'roles.update',
    'roles.delete',
    'attachments.read',
    'attachments.upload',
    'attachments.delete',
    // Masters Page
    'masters.department.read',
    'masters.department.create',
    'masters.department.update',
    'masters.department.delete',
    'masters.machine.read',
    'masters.machine.create',
    'masters.machine.update',
    'masters.machine.delete',
    'masters.productionline.read',
    'masters.productionline.create',
    'masters.productionline.update',
    'masters.productionline.delete',
    'masters.skill.read',
    'masters.skill.create',
    'masters.skill.update',
    'masters.skill.delete',
    // 4M Guided Setup
    'guidedsetup.man.read',
    'guidedsetup.man.update',
    'guidedsetup.machine.read',
    'guidedsetup.machine.update',
    'guidedsetup.method.read',
    'guidedsetup.method.update',
    'guidedsetup.material.read',
    'guidedsetup.material.update',
  ],
  Manager: [
    'dashboard.view',
    'changes.read',
    'changes.create',
    'changes.update',
    'approvals.read',
    'approvals.approve',
    'attachments.read',
    'attachments.upload',
    'attachments.delete',
    // Masters Page (read-only)
    'masters.department.read',
    'masters.machine.read',
    'masters.productionline.read',
    'masters.skill.read',
    // 4M Guided Setup (read/update)
    'guidedsetup.man.read',
    'guidedsetup.man.update',
    'guidedsetup.machine.read',
    'guidedsetup.machine.update',
    'guidedsetup.method.read',
    'guidedsetup.method.update',
    'guidedsetup.material.read',
    'guidedsetup.material.update',
  ],
  User: [
    'dashboard.view',
    'changes.read',
    'changes.create',
    'changes.update',
    'approvals.read',
    'attachments.read',
    'attachments.upload',
    // Masters Page (read-only)
    'masters.department.read',
    'masters.machine.read',
    'masters.productionline.read',
    'masters.skill.read',
    // 4M Guided Setup (read-only)
    'guidedsetup.man.read',
    'guidedsetup.machine.read',
    'guidedsetup.method.read',
    'guidedsetup.material.read',
  ],
};
