-- Documentation schema aligned with Sequelize models
-- Runtime schema is generated by Sequelize sync in backend/src/server.js

CREATE DATABASE IF NOT EXISTS change_management;
USE change_management;

CREATE TABLE IF NOT EXISTS roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name ENUM('SuperAdmin', 'Admin', 'Manager', 'User') NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role_id INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS change_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type ENUM('Man', 'Machine', 'Method', 'Material') NOT NULL,
  request_no VARCHAR(50),
  request_date DATE,
  production_line VARCHAR(120),
  machine VARCHAR(120),
  sub_type VARCHAR(120),
  current_operator VARCHAR(120),
  proposed_operator VARCHAR(120),
  required_skills TEXT,
  proposed_operator_skill_status ENUM('Matched', 'Gap'),
  training_required BOOLEAN NOT NULL DEFAULT FALSE,
  training_status ENUM('Not Required', 'Pending', 'Scheduled', 'Completed') DEFAULT 'Not Required',
  training_notes TEXT,
  compliance_requirements TEXT,
  action_plan_required BOOLEAN NOT NULL DEFAULT FALSE,
  action_plan_notes TEXT,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  current_state TEXT NOT NULL,
  proposed_change TEXT NOT NULL,
  reason TEXT NOT NULL,
  old_value TEXT,
  new_value TEXT,
  impact_analysis TEXT NOT NULL,
  quality_impact ENUM('Low', 'Medium', 'High'),
  cost_impact ENUM('Low', 'Medium', 'High'),
  delivery_impact ENUM('Low', 'Medium', 'High'),
  safety_impact ENUM('Low', 'Medium', 'High'),
  monitoring_period VARCHAR(120),
  quality_result VARCHAR(200),
  defect_rate VARCHAR(50),
  monitoring_comments TEXT,
  risk_level ENUM('Low', 'Medium', 'High', 'Critical') NOT NULL,
  department VARCHAR(120) NOT NULL,
  status ENUM('Pending', 'Approved', 'Rejected', 'Implemented', 'Closed') NOT NULL DEFAULT 'Pending',
  created_by INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_requests_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS approvals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  request_id INT NOT NULL,
  approver_id INT NOT NULL,
  status ENUM('Pending', 'Approved', 'Rejected') NOT NULL DEFAULT 'Pending',
  remarks TEXT NULL,
  approved_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_approvals_request FOREIGN KEY (request_id) REFERENCES change_requests(id) ON DELETE CASCADE,
  CONSTRAINT fk_approvals_user FOREIGN KEY (approver_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  request_id INT NOT NULL,
  user_id INT NOT NULL,
  action ENUM('CREATED', 'UPDATED', 'APPROVED', 'REJECTED', 'IMPLEMENTED') NOT NULL,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_audit_request FOREIGN KEY (request_id) REFERENCES change_requests(id) ON DELETE CASCADE,
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS attachments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  request_id INT NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_attachments_request FOREIGN KEY (request_id) REFERENCES change_requests(id) ON DELETE CASCADE
);

CREATE INDEX idx_change_status ON change_requests(status);
CREATE INDEX idx_change_type ON change_requests(type);
CREATE INDEX idx_change_department ON change_requests(department);
CREATE INDEX idx_approval_request ON approvals(request_id);
CREATE INDEX idx_audit_request ON audit_logs(request_id);